# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

# Comment this line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

# Pods for NoughtsAndCrosses

target 'NoughtsAndCrosses' do

  pod 'Alamofire', '~> 3.4'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'

end